name: tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - checkv=1.0.1
  - cd-hit=4.6.8
  - trimmomatic=0.38
  - bowtie2=2.4.2
  - megahit=1.1.3
  - blast
  - coverm
  - samtools >=1.9
  - coreutils
  - minimap2 >=2.24
  - bwa >=0.7.17
  - bwa-mem2
  - fastani >= 1.3
  - extern
