name: tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - checkv=1.0.1
  - cd-hit=4.6.8
  - diamond=2.1.8
  - trimmomatic=0.38
  - bowtie2=2.4.2
  - megahit=1.1.3
  - blast=2.13.0
  - coverm
  - samtools >=1.9
  - coreutils
  - minimap2 >=2.24
  - bwa >=0.7.17
  - bwa-mem2
  - dashing >= 0.4.0, < 1.0 # dashing 1.0 build gives illegal instruction errors.
  - fastani >= 1.3
  - strobealign >= 0.11.0 # newest version at time of implementation
  - extern
